# Deploy to Firebase Hosting when code is merged into the production branch
# ------------------------------------------------------------
# Automatically created by Firebase CLI and amended for:
#   • Node setup
#   • npm dependency install
#   • npm cache to speed up builds
# ------------------------------------------------------------

name: Deploy to Firebase Hosting on merge

on:
  push:
    # 👇 Replace main with master if that’s your production branch
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Check out repo
      - uses: actions/checkout@v4

      # 2️⃣  Cache npm files to make repeat installs faster
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 3️⃣  Install the same Node you use locally
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x          # change if you use another major version

      # 4️⃣  Install deps & build
      - run: npm ci
      - run: npm run build

      # 5️⃣  Deploy to Firebase Hosting (live channel)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CALCCHAIN }}
          channelId: live
          projectId: calcchain
