# Deploy a preview channel for every pull request
# ------------------------------------------------------------
# Automatically created by Firebase CLI and amended for:
#   • Node setup
#   • npm dependency install
#   • npm cache
# ------------------------------------------------------------

name: Deploy to Firebase Hosting on PR
on: pull_request

permissions:
  checks: write          # so the action can annotate the PR
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    # Only run if the PR comes from the same repo (skip forks)
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci
      - run: npm run build

      # Deploys to an auto-generated preview channel like
      # https://<branch-name>--calcchain.web.app
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CALCCHAIN }}
          projectId: calcchain
